### ISSUE TITLE
As of 1.15 beehive no longer has underscore in its name so any json file that uses it will have problems

### ISSUE THREAD

**Issue by Gryjlfkagor** [Aeldrion/AESTD#4]
in the opaque.json file the beehive block has an underscore in it and since it was changed in 1.15 the rest of the file useless. Not a big problem, especially since it is specified in the files that it is meant for earlier version, it is just something to note for people trying to use it in newer versions :)

**Comment by RossBoss7474** [comment]
Hey look at that I found out about pull requests, I guess I will fix it myself?
